seqlens:        [{day: 5}] # although not a param for model, but can be different values(dict of SEQLEN) #
objective:      [RMSE]
learning_rate:  [0.3] 
max_depth:      [6 , 8 , 10]
monotone_constraints:     [0]
l2_leaf_reg:      [1.0e-05]
random_strength : [1.0]