availables: 
  - csi300
  - csi500
  - csi800
  - csi1000
  - csi2000
defaults:
  - csi500
  - csi1000
categories:
  - default
  - none
  - market
  - csi300
  - csi500
  - csi800
  - csi1000
  - csi2000