utility:
  lambda: 100.0
  trade_cost_rho: 0.001

equity:
  target_position:  1.0
  target_value:     null
  add_position:     null
  add_value:        null

benchmark:
  benchmark:
    csi800:     1.0

pool:
  allow:        null
  basic:        null
  ignore:       null
  no_buy:       null
  no_ldev:      null
  no_sell:      null
  no_udev:      null
  prohibit:     null
  warning:      null
  shortable:    null

range:
  ffmv.abs:     [null, null]
  ffmv.pct:     [0.1 , null]
  cp.abs:       [null, null]
  cp.pct:       [null, null]
  #amt.abs:      [null, null]
  #amt.pct:      [0.1 , null]
  #bv.abs:       [null, null]
  #bv.pct:       [0.1 , null]  

induspool:
  no_buy:       null
  no_net_buy:   null
  no_net_sell:  null
  no_sell:      null

board:
  csi:          [null , null]
  kcb:          [null , null]
  shse:         [null , null]
  szse:         [null , null]

limitation:
  ignore_spec_risk: false
  kcb_no_buy:       false
  kcb_no_sell:      false
  no_st:            true
  list_days:        63
  te_constraint:    null
  
bound:
  abs:          [-0.01 , 0.1]
  rel:          [-0.01 , 0.01]
  por:          [null , null]

industry:
  abs:          [null , null]
  rel:          [-0.01, 0.01]
  por:          [null , null]

style:
  abs:          [null , null]
  rel:          [-0.5 , 0.5]
  por:          [null , null]
  size.rel:     [-0.25, 0.25]
  beta.rel:     [-0.25, 0.25]

component:
  bsizedev1:    [null , null]
  bsizedev2:    [null , null]
  component:    [-0.2 , null]

turnover:
  double:       null
  single:       0.2

short:
  short_cost:     null
  short_position: null