recommended_explorer: "chrome"
page_title: "Learndl"
pending_features: []
auto_refresh_interval: 0 # seconds

navigation_position: "both" # "sidebar", "both"

task_queue_backend_refresh_interval: 5 # seconds
task_starting_timeout: 20 # seconds