from __future__ import annotations

from abc import ABC , ABCMeta

from src.proj import Logger

__all__ = ['BaseStreamLine' , 'ModelStreamLine' , 'BaseStreamLineMeta']

class BaseStreamLine(ABC):
    """Base class for all model stream lines , e.g. trainer, predictor, data module, etc."""
    @staticmethod
    def base_hooks():
        return [hook for hook in dir(BaseStreamLine) if hook.startswith(('stage_' , 'on_'))]
    def stage_data(self): ...
    def stage_fit(self):  ...
    def stage_test(self): ...
    def on_configure_model(self): ...
    def on_summarize_model(self): ...
    def on_data_end(self): ... 
    def on_data_start(self): ... 
    def on_after_fit_epoch(self): ... 
    def on_after_backward(self): ... 
    def on_before_backward(self): ... 
    def on_before_clip_gradients(self): ... 
    def on_before_save_model(self): ... 
    def on_before_fit_epoch_end(self): ... 
    def on_fit_end(self): ... 
    def on_fit_epoch_end(self): ... 
    def on_fit_epoch_start(self): ... 
    def on_fit_model_end(self): ... 
    def on_fit_model_start(self): ... 
    def on_fit_model_date_end(self): ... 
    def on_fit_model_date_start(self): ... 
    def on_fit_start(self): ...
    def on_test_batch_end(self): ...
    def on_test_batch_start(self): ... 
    def on_test_end(self): ... 
    def on_test_model_end(self): ... 
    def on_test_model_start(self): ... 
    def on_test_model_date_end(self): ... 
    def on_test_model_date_start(self): ... 
    def on_test_submodel_end(self): ... 
    def on_test_submodel_start(self): ... 
    def on_test_start(self): ... 
    def on_train_batch_end(self): ... 
    def on_train_batch_start(self): ... 
    def on_train_epoch_end(self): ... 
    def on_train_epoch_start(self): ... 
    def on_validation_batch_end(self): ... 
    def on_validation_batch_start(self): ...
    def on_validation_epoch_end(self): ...
    def on_validation_epoch_start(self): ...
    def on_before_data_start(self): ...
    def on_after_data_end(self): ...
    def on_before_fit_start(self): ...
    def on_after_fit_end(self): ...
    def on_before_test_start(self): ...
    def on_before_test_end(self): ...
    def on_after_test_end(self): ...

class BaseStreamLineMeta(ABCMeta): 
    def __new__(cls, name, bases, attrs):
        new_cls = super().__new__(cls, name, bases, attrs)

        # check if the class defines extra hooks
        current = set([hook for hook in dir(new_cls) if hook.startswith(('stage_' , 'on_'))])
        base_hooks = set(getattr(new_cls, 'base_hooks', lambda: [])())
        extra = current - base_hooks
        if extra:
            Logger.warning(f'{new_cls.__name__} defines extra hooks: {extra}')

        # check if the class defines placeholdernames for hooks
        placeholder_names = set([hook for hook in dir(new_cls) if hook.startswith(('_raw_'))])
        if placeholder_names:
            Logger.warning(f'{new_cls.__name__} defines placeholder names for hooks: {placeholder_names}')
        return new_cls

class ModelStreamLine(BaseStreamLine, metaclass=BaseStreamLineMeta):
    """Base class for all model stream lines , e.g. trainer, predictor, data module, etc."""
    def execute_hook(self , hook : str):
        getattr(self , hook)()