default:
  top:
    n_best: 50
    turn_control: 0.1
    buffer_zone: 0.8
    no_zone: 0.5
    indus_control: 0.1

  screen:
    sorter: gru_day_V1
    screen_ratio: 0.5
    
  revscreen:
    screener: gru_day_V1
    screen_ratio: 0.5
    
  reinforce:
    screener: gru_day_V1
    screen_ratio: 0.5