model:
  # main model configs ----------------------------------------------------------------
  name          : gru_week # any name or null
  module        : resnet_gru  # any of [nn defined in src/algo/nn/api.py] or ['boost' , 'lgbm' , 'ada' , 'xgboost' , 'catboost']
  submodels     : [best] # subset of ['best' , 'swalast' , 'swabest'] , but for boost , only use best

  # labels specification ------------------------------------------------------------
  # rtn : raw return | std : standardized return | res : risk model residual
  # if module is nn , use multiloss combination of the labels
  # if module is boost , only use the first label
  labels: 
    - std_lag1_10 # any of [res_lag1_10, res_lag1_20, rtn_lag1_10, rtn_lag1_20, std_lag1_10, std_lag1_20]
    - rtn_lag1_10 

input:  # input specification ----------------------------------------------------------------
  type: data # [data , hidden , factor] , specify below
  data.types: week # ['day+30m' , 30m , day , ...] , use if input_type is data
  sequence.lens: {week: 50}
  sequence.steps: {week: 5}

algo:
  
