objective:      [regression]
linear_tree:    [True]
learning_rate:  [0.3] 
lambda_l2:      [1.0e-05]
alpha:          [1.0e-07]
num_leaves:     [31]
max_depth:      [6]
min_sum_hessian_in_leaf:  [1]
feature_fraction:         [0.6]
bagging_fraction:         [0.75]
force_col_wise:           [True]
monotone_constraints:     [0]