LearnRateReset:     {'num_reset' : 2 , 'trigger' : 40 , 'recover_level' : 1. , 'speedup2x' : true , }
CallbackTimer:      {}
EarlyStoppage:      {'peak_patience' : 20 , 'converge_patience' : 5 , 'converge_dataset' : 'valid'}
BadAttemptRetrain:  {'early_exit' : 30 , 'min_ic' : 0.05 , 'max_attempt' : 4 , 'max_nan_redo' : 4 , 'lr_multiplier':[1 , 0.3 , 0.1 , 0.03 , 0.01]}
StatusDisplay:      {}
SummaryWriter:      {}
DetailedAlphaAnalysis:  {}
MemoryOptimization: {'batch_interval' : 20}