short_test:
  model.beg_date:   20241101
  model.end_date:   20250331 # 20240229
  model.window: 240
  train.max_epoch:  3
  input.filter.secid: random.200
  input.filter.date: 20230101-20250331
  callbacks.DetailedAlphaAnalysis:  {tasks: ['factor']}
  callbacks.BadAttemptRetrain:  {max_attempt: 2}
  train.callbacks:
    - StatusDisplay
    - SummaryWriter
    - BasicTestResult
    - DetailedAlphaAnalysis
    - BadAttemptRetrain
    - LearnRateReset
transformer:
  callbacks.LearnRateReset:  {'num_reset' : 1 , 'trigger' : 60 , 'recover_level' : 1. , 'speedup2x' : true , }