hidden_dim:     [64] #  2**5
seqlens:        [{'day': 30 , '30m': 30 , 'dms': 30}] # although not a param for model, but can be different values(dict of SEQLEN) #
seq_len:        [30]
dropout:        [0.1]
attn_dropout:   [0.1]
num_output:     [1]
shared_embedding: True
shared_head:      [False]
revin:          [True]
act_type:       gelu
patch_len :     [4,5,6]
stride :        [2,2,3]
n_layers:       2
n_heads:        [16]
d_ff:           [64]
