REG_MODELS:
  - name: gru_day
    submodel: swalast
    num: 0
    alias: gru_day_V0
    
  - name: gruRTN_day
    submodel: swalast
    num: 0
    alias: gruRTN_day_V0

  - name: gru_avg
    submodel: swalast
    num: all
    alias: gru_day_V1

HID_MODELS:
  - name: gru_day
    submodels: [best]
    nums: NULL
    alias: gru_day_V0
      