model:
  # main model configs ----------------------------------------------------------------
  module        : astgnn_idio  # any of [nn defined in src/algo/nn/api.py] or ['boost' , 'lgbm' , 'ada' , 'xgboost' , 'catboost']
  submodels     : [best] # subset of ['best' , 'swalast' , 'swabest'] , but for boost , only use best

  # labels specification ------------------------------------------------------------
  # rtn : raw return | std : standardized return | res : risk model residual
  # if module is nn , use multiloss combination of the labels
  # if module is boost , only use the first label
  labels: 
    - std_lag1_10 # any of [res_lag1_10, res_lag1_20, rtn_lag1_10, rtn_lag1_20, std_lag1_10, std_lag1_20]
    - rtn_lag1_10


input:  # input specification ----------------------------------------------------------------
  type: data # [data , hidden , factor] , specify below
  data.types: 15m+day+style # ['15m+day+style' , 15m , day , style , ...] , use if input_type is data
  sequence.lens: {15m: 30 , day: 30 , style: 30}
  sequence.steps: {15m: 1 , day: 1 , style: 1}

train:
  criterion.weight:
    fit:    'polar'

algo:
  astgnn_idio:
    resnet_projector: true
    beta_into_pred: [true, false]
  
