model:
  # main model configs ----------------------------------------------------------------
  module        : xgboost  # any of [nn defined in src/algo/nn/api.py] or ['boost' , 'lgbm' , 'ada' , 'xgboost' , 'catboost']
  submodels     : [best] # subset of ['best' , 'swalast' , 'swabest'] , but for boost , only use best

  # labels specification ------------------------------------------------------------
  # rtn : raw return | std : standardized return | res : risk model residual
  # if module is nn , use multiloss combination of the labels
  # if module is boost , only use the first label
  labels: 
    - rtn_lag1_10 # any of [res_lag1_10, res_lag1_20, rtn_lag1_10, rtn_lag1_20, std_lag1_10, std_lag1_20]
    
  module.boost.optuna: False

  window   : 720
  interval : 20

input:
  # input specification ----------------------------------------------------------------
  type: hidden # [data , hidden , factor] , specify below

  hidden.types: # list of hidden states , use if input_type is hidden
    - gru@gru_day_new_rtn@2@0@best # directory @2, model number 0

train:
  boost:
    param:
      objective: mse # null , mse , mae , rank
    weight:
      cs_type: top
      ts_type: lin
      bm_type: null
    # valid_metric:
    #   name: global2top
    #   glb_multiplier: 5.0
    #   top_quantile: 0.1

  dataloader.shuffle_option: static
  dataloader.train_ratio: 0.80

algo:
  xgboost:
    seqlens:        [{day: 1}]
    learning_rate:  [0.05]
    num_boost_round: [2000]
    early_stopping: [100]
    max_depth:      [4]
    min_child_weight: [200] # minimum sum of Hessians, not a row count
    reg_lambda:     [10.0]
    reg_alpha:      [0.1]
    subsample:      [0.8]
    colsample_bytree: [0.8]
    tree_method:    [hist]
    max_bin:        [127]
