# models of db saved models : 
# prediction name
#   type: db | factor | pred
#   src: db_src          .db_src or factor or pred
#   key: db_key          .if db_src is db, db_key is the key of the db, otherwise it is the name of the factor or pred
#   col: column_name     .use feature to load the data

scores_v0:
  src: sellside
  key: dongfang.scores_v0
  col: avg

master_combined:
  src: sellside
  key: huatai.master_combined
  col: master_combined
