# models for hidden extraction : 
# hidden name
#   name: module_name
#   submodels: submodel_types , best , swalast , swabest
#   nums: a list of valid numbers or NULL (all)

gru_day_V0: 
  name: gru_day
  submodels: [best]
  nums: NULL
      