focused_ports:
  - use_daily

# accepted fields:
#   alpha: str or comma separated strings
#   components (if it is a composite alpha): list of str or comma separated strings
#   weights: null / equal is equal weights , or list of floats
#   universe: str , default is 'top-1000'
#   category: Literal['top' , 'screen' , 'reinforce'] , default is 'top' (automatically fallback if screener not provided)
#   top_num: int , default is 50
#   freq: int or 'd' / 'w' / 'm' , default is 1
#   test_start (for backtest): int , default is 20190101
#   test_end (for backtest): int , default is -1
#   benchmark: str , default is 'csi500'
#   exclusion: str , default is 'st_bse_lowprice_loser_warnst'
#   sorter: str | list[str] | None , default is None
#   screener: str | list[str] | None , default is None
#   screen_ratio: float , default is 0.5
#   buffer_zone: float , default is 0.8
#   no_zone: float , default is 0.5
#   indus_control: float , default is 0.1

trading_ports:
  use_daily:
    alpha: 
      - factor@ht_master_combined
      - factor@df_scores_v0
      - factor@df_scores_v3
      - gru_day_V1

  master_daily:
    alpha: factor@ht_master_combined

  gru_daily:
    alpha: gru_day_V1

backtest_ports:
  use_daily.backtest:
    alpha: big_combine
    components:
      - sellside@huatai.master_combined@master_combined
      - factor@df_scores_v0
      - gru_day_V1

  use_daily.backtest1:
    alpha: 
      - factor@ht_master_combined
      - factor@df_scores_v0
      - gru_day_V1

  use_daily2.backtest:
    alpha: 
      - factor@ht_master_combined
      - factor@df_scores_v0
      - factor@df_scores_v3
      - gru_day_V1

  event_factor_momentum.backtest:
    alpha: factor@event_factor_momentum
    # category: screen

  add_model.gru_week:
    alpha: 
      - gru_week

  add_model.gru_30m:
    alpha: 
      - gru_30m

  add_model.gru_dfl2:
    alpha: 
      - gru_dfl2

  add_model.gru_dfl2cs:
    alpha: 
      - gru_dfl2cs

  test_backtest.0:
    alpha: 
      - gru_dfl2
      - gru_dfl2cs

  test_backtest.1:
    alpha: 
      - gru_dfl2
      - gru_dfl2cs
    screener:
      - gru_week
      - gru_30m

  test_backtest.2:
    alpha: 
      - gru_dfl2
      - gru_dfl2cs
    screener:
      - gru_30m

  test_backtest.3:
    alpha: 
      - gru_dfl2
      - gru_dfl2cs
    screener:
      - gru_week

  test_backtest.4:
    alpha: 
      - gru_dfl2
      - gru_dfl2cs
    screener:
      - gru_dfl2
      - gru_dfl2cs