indus:
  IT服务Ⅱ: software
  一般零售: retail
  专业工程: construct
  专业服务: leisure
  专业连锁Ⅱ: retail
  专用设备: machine
  个护用品: health
  中药Ⅱ: health
  乘用车: auto
  互联网电商: retail
  休闲食品: food
  体育Ⅱ: leisure
  保险Ⅱ: financial
  元件: electronic
  光伏设备: power
  光学光电子: electronic
  其他家电Ⅱ: appliance
  其他电子Ⅱ: electronic
  其他电源设备Ⅱ: power
  养殖业: agro
  军工电子Ⅱ: defense
  农业综合Ⅱ: agro
  农产品加工: agro
  农化制品: chemical
  农商行Ⅱ: bank
  冶钢原料: steel
  出版: media
  动物保健Ⅱ: agro
  包装印刷: light
  化妆品: health
  化学制品: chemical
  化学制药: health
  化学原料: chemical
  化学纤维: chemical
  医疗器械: health
  医疗服务: health
  医疗美容: health
  医药商业: health
  半导体: electronic
  厨卫电器: appliance
  商用车: auto
  国有大型银行Ⅱ: bank
  地面兵装Ⅱ: defense
  城商行Ⅱ: bank
  基础建设: construct
  塑料: chemical
  多元金融: financial
  家居用品: light
  家电零部件Ⅱ: appliance
  小家电: appliance
  小金属: nonferrous
  工业金属: nonferrous
  工程咨询服务Ⅱ: construct
  工程机械: machine
  广告营销: media
  影视院线: media
  房地产开发: estate
  房地产服务: estate
  房屋建设Ⅱ: construct
  摩托车及其他: auto
  教育: leisure
  数字媒体: media
  文娱用品: light
  旅游及景区: leisure
  旅游零售Ⅱ: retail
  普钢: steel
  服装家纺: textile
  林业Ⅱ: agro
  橡胶: chemical
  水泥: cement
  汽车服务: auto
  汽车零部件: auto
  油服工程: petro
  油气开采Ⅱ: petro
  消费电子: electronic
  渔业: agro
  游戏Ⅱ: media
  炼化及贸易: petro
  焦炭Ⅱ: coal
  煤炭开采: coal
  照明设备Ⅱ: appliance
  燃气Ⅱ: utility
  物流: transport
  特钢Ⅱ: steel
  环保设备Ⅱ: public
  环境治理: public
  玻璃玻纤: material
  生物制品: health
  电力: utility
  电子化学品Ⅱ: electronic
  电机Ⅱ: power
  电池: power
  电网设备: power
  电视广播Ⅱ: media
  白色家电: appliance
  白酒Ⅱ: liqor
  种植业: agro
  纺织制造: textile
  综合Ⅱ: complex
  股份制银行Ⅱ: bank
  能源金属: nonferrous
  自动化设备: machine
  航天装备Ⅱ: defense
  航海装备Ⅱ: defense
  航空机场: airline
  航空装备Ⅱ: defense
  航运港口: marine
  装修建材: material
  装修装饰Ⅱ: construct
  计算机设备: hardware
  证券Ⅱ: financial
  调味发酵品Ⅱ: food
  贵金属: nonferrous
  贸易Ⅱ: retail
  轨交设备Ⅱ: machine
  软件开发: software
  通信服务: telecom
  通信设备: telecom
  通用设备: machine
  造纸: light
  酒店餐饮: leisure
  金属新材料: nonferrous
  铁路公路: transport
  非白酒: food
  非金属材料Ⅱ: chemical
  风电设备: power
  食品加工: food
  饮料乳品: food
  饰品: textile
  饲料: agro
  黑色家电: appliance
