hidden_dim:     [32] #  2**5
seqlens:        [{'day': 30 , '30m': 30 , 'dms': 30}] # although not a param for model, but can be different values(dict of SEQLEN) #
hist_loss_seq_len:  [60]
hist_loss_horizon:  [20]
num_states:     [3]
dropout:        [0.1]
rnn_layers:     [2]
rnn_type:       ['lstm']