hidden_dim:     [32,64] #  2**5
seqlens:        [{'day': 30 , '30m': 30 , 'dms': 30}] # although not a param for model, but can be different values(dict of SEQLEN) #
seq_len:        [30]
tra_seqlens:    [{'hist_loss': 40}]
dropout:        [0.1]
attn_dropout:   [0.1]
num_output:     [1]
patch_len : 5
stride : 2 
shared_embedding: True
shared_head:      False
revin:            True
n_layers:       3 
n_heads:        16
d_ff:           256
