# most frequently changing variables
mem_storage: true 
random_seed: null
short_test:  false

model_name: null # null
model_module: factor_vae # tra_lstm2 # 'LSTM' # 'TRA_LSTM' # 'GeneralRNN' # patch_tst # lgbm
model_types: [best , swalast , swabest]
model_data_type: day # 'day+30m' , 30m
model_data_prenorm:
  day: {'divlast' : True  , 'histnorm' : True}
labels: 
  - std_lag1_10 # rtn_lag1_10 # std_lag1_10
  - std_lag1_20
callbacks:
  DynamicDataLink :   {}
  ResetOptimizer:     {'num_reset' : 2 , 'trigger' : 40 , 'recover_level' : 1. , 'speedup2x' : true , }
  CallbackTimer:      {}
  EarlyStoppage:      {'patience' : 20}
  ValidationConverge: {'patience' : 5 , 'eps' : 1.0e-5} 
  EarlyExitRetrain:   {'earliest' : 10 , 'max_attempt' : 4 , 'lr_multiplier':[1 , 0.1 , 10 , 0.01 , 100 , 1]}
  NanLossRetrain:     {'max_attempt' : 4}
  BatchDisplay:       {}
  StatusDisplay:      {}
  #CudaEmptyCache:     {} 
  #TrainConverge:      {'patience' : 5 , 'eps' : 1.0e-5} 
  #FitConverge:        {'patience' : 5 , 'eps' : 1.0e-5}
  #CudaEmptyCache:     {'batch_interval' : 20}

train_param:
  dataloader:
    sample_method:   train_shuffle # total_shuffle , sequential , both_shuffle , train_shuffle
    shuffle_option:  epoch
    train_ratio:     0.8
  trainer:
    optimizer: {'name' : 'Adam' , 'param' : {} ,}  #{'name' : 'SGD' , 'param' : {} ,}
    scheduler: {'name' : 'cycle' , 'param' : {'base_lr': 1.0e-7 , 'step_size_up': 4} ,}  #{'name' : 'SGD' , 'param' : {} ,}
    learn_rate:
      base:    0.005
      transfer_multiplier:   {'encoder' : 0.1 , 'decoder' : 1.0, } 
    gradient:  {'clip_value' : 10.0}
  criterion:
    loss:      mse  # mse, pearson, ccc
    score:     spearman # mse, pearson, ccc, spearman
    penalty:   
      hidden_corr: 
        lamb : 0.001
      tra_opt_transport: 
        lamb : 0.01
        rho : 0.999
    weight:
      fit:    'equal' # 'top'
      test:   'equal' # 'top'
  transfer:    false
  multilosses:
    type: hybrid
    param_dict:
      dwa: {'tau' : 2}
      ruw: {'phi' : null}
      ewa: {}
      gls: {}
      rws: {}
      hybrid: {'phi' : null , 'tau' : 2}

beg_date:   20170103
end_date:   99991231
input_span: 2400
interval:   120
max_epoch:  200
verbosity:  2
batch_size: 10000
input_step_day: 5
skip_horizon: &skip_horizon 20 

# tra model
lgbm_ensembler: false
tra_switch:  true
buffer_type: tra
buffer_param: 
  tra_num_states: &tra_num_states 5
tra_param:
  tra_num_states : *tra_num_states
  tra_horizon : *skip_horizon
  
# torch utility
allow_tf32: true
detect_anomaly: false
precision:  float # double , bfloat16

on_short_test:
  beg_date:   20170101
  end_date:   20170228 # 20170228
  input_span: 240
  max_epoch:  3
  verbosity:  10
on_transformer:
  train_param:
    trainer:
      callbacks:
        ResetOptimizer:     {'num_reset' : 1 , 'trigger' : 60 , 'recover_level' : 1. , 'speedup2x' : true , }