"""
Definition of MetricAggregator:
In scenario of multi-element metrics generated by LossFunction and AccuracyFunction, this class is used to perform aggregation, comparison and selection on them.
Aggregation includes:
- naive sum (default)
- weighted sum (inject a dict of weights)
- if it is accuracy, a custom function (inject a callable)
Injected Aggregator: dict or callable[dict[str,float] -> float]
- All injections shall be sticky, which means they persist until next injection or reset.
- All injections shall be stored before reset, but the last injection shall be used for later calculation.
Comparison:
- when compare, if not provided, use the latest injected aggregator.
- compare epochs of a fitting attempt (in validation dataset mostly) to select the best one (early stopping, phase transition)
- compare attempts of model to select the best one (model selection)
"""
from __future__ import annotations
import pandas as pd
import numpy as np
import torch
from typing import Callable , Any , Literal , Iterable

from .metric_result import EpochMetricResult

__all__ = ['AggregatorType' , 'AccuracyAggregator' , 'LossAggregator' , 'MetricAggregator']

AggregatorType = dict[str,float] | Callable[[dict[str,float]],float]

class AccuracyAggregator:
    def __init__(self , aggregator :  AggregatorType | None = None):
        self.aggregator = aggregator or {}

    def __repr__(self):
        return f'{self.__class__.__name__}(aggregator={self.aggregator})'

    def accuracy(self , accuracies : dict[str | Any ,float]) -> float:
        if not accuracies:
            return -np.inf
        if isinstance(self.aggregator , dict):
            return sum([accu * self.aggregator.get(key , 1.) for key,accu in accuracies.items()])
        elif isinstance(self.aggregator , Callable):
            return self.aggregator(accuracies)
        else:
            raise ValueError(f'Invalid aggregator type: {type(self.aggregator)}')

class LossAggregator:
    def __init__(self , aggregator : AggregatorType | None = None):
        aggregator = aggregator or {}
        assert isinstance(aggregator , dict) , f'loss aggregator should be a dict, but got {type(aggregator)}'
        assert all(weight >= 0 for weight in aggregator.values()) , f'loss aggregator should be non-negative, but got {aggregator}'
        self.aggregator = aggregator

    def __repr__(self):
        return f'{self.__class__.__name__}(aggregator={self.aggregator})'

    def loss_weights(self , losses : dict[str | Any,Any] | Iterable[str | Any]) -> dict[str,float]:
        return {key:self.aggregator.get(key , 1.) for key in losses}

    def loss(self , losses : dict[str | Any,torch.Tensor]) -> torch.Tensor:
        all_losses = torch.concatenate([loss.flatten() * self.aggregator.get(key , 1.) for key,loss in losses.items()])
        return all_losses.sum() if all_losses.numel() > 0 else torch.Tensor([0]).requires_grad_(True)

    def loss_item(self , losses : dict[str | Any,float]) -> float:
        if not losses:
            return 0.
        return sum([loss * self.aggregator.get(key , 1.) for key,loss in losses.items()])
    

class MetricAggregator:
    """perform aggregation operations on a list of metrics (loss and accuracy)"""
    def __init__(self):
        self.accuracy_aggregators : list[AccuracyAggregator] = [AccuracyAggregator()]
        self.loss_aggregators : list[LossAggregator] = [LossAggregator()]

    def __repr__(self):
        return f'{self.__class__.__name__}(accuracy={self.accuracy_aggregator},loss={self.loss_aggregator})'

    def accuracy_aggregator(self , aggregator :  AggregatorType | None = None) -> AccuracyAggregator:
        if aggregator is None:
            return self.accuracy_aggregators[-1]
        return AccuracyAggregator(aggregator)

    def loss_aggregator(self , aggregator : AggregatorType | None = None) -> LossAggregator:
        if aggregator is None:
            return self.loss_aggregators[-1]
        return LossAggregator(aggregator)

    def loss_weights(self , losses : dict[str , Any]) -> dict[str,float]:
        return self.loss_aggregators[-1].loss_weights(losses)

    def inject(self , metric_type : Literal['accuracy','loss'] , aggregator :  AggregatorType | None = None):
        if aggregator is None:
            aggregator = {}
        if metric_type == 'accuracy':
            self.accuracy_aggregators.append(AccuracyAggregator(aggregator))
        elif metric_type == 'loss':
            self.loss_aggregators.append(LossAggregator(aggregator))
        else:
            raise ValueError(f'Invalid metric: {metric_type}')

    def reset(self):
        self.accuracy_aggregators.clear()
        self.loss_aggregators.clear()
        self.accuracy_aggregators.append(AccuracyAggregator())
        self.loss_aggregators.append(LossAggregator())

    def total_accuracy(self , accuracies : dict[str,float], aggregator : AggregatorType | None = None) -> float:
        agg = self.accuracy_aggregator(aggregator)
        return agg.accuracy(accuracies)

    def total_accuracies(self , accuracy_table : pd.DataFrame , aggregator : AggregatorType | None = None) -> np.ndarray:
        agg = self.accuracy_aggregator(aggregator)
        accuracies = accuracy_table.to_dict(orient = 'records')
        return np.array([agg.accuracy(accuracy) for accuracy in accuracies])

    def total_loss(self , losses : dict[str,torch.Tensor] , aggregator : dict[str,float] | None = None) -> torch.Tensor:
        agg = self.loss_aggregator(aggregator)
        return agg.loss(losses)

    def total_loss_item(self , losses : dict[str,float] , aggregator : dict[str,float] | None = None) -> float:
        agg = self.loss_aggregator(aggregator)
        return agg.loss_item(losses)

    def total_losses(self , loss_table : pd.DataFrame , aggregator : AggregatorType | None = None) -> np.ndarray:
        agg = self.loss_aggregator(aggregator)
        losses = loss_table.to_dict(orient = 'records')
        return np.array([agg.loss_item(loss) for loss in losses])

    def argbest(
        self , 
        metrics : pd.DataFrame | Iterable[EpochMetricResult | None] , 
        metric_type : Literal['accuracy','loss'] = 'accuracy' , 
        aggregator : AggregatorType | None = None
    ) -> int:
        """compare accuracies, return the index of the best one"""
        if isinstance(metrics , pd.DataFrame):
            all_metrics = metrics.to_dict(orient = 'records')
        else:
            all_metrics = [metric.metrics('valid' , metric_type) if metric else {} for metric in metrics]

        if metric_type == 'accuracy':
            agg = self.accuracy_aggregator(aggregator)
            totals = np.array([agg.accuracy(accuracy) for accuracy in all_metrics])
            return np.argmax(totals).item()
        elif metric_type == 'loss':
            agg = self.loss_aggregator(aggregator)
            totals = np.array([agg.loss_item(loss) for loss in all_metrics])
            return np.argmin(totals).item()
        else:
            raise ValueError(f'Invalid metric: {metric_type}')

    def larger(
            self , metric0 : dict[str|Any,float] | float | EpochMetricResult , metric1 : dict[str|Any,float] | float | EpochMetricResult , 
            metric_type : Literal['accuracy','loss'] = 'accuracy' , aggregator : AggregatorType | None = None
        ) -> bool:
        if isinstance(metric0 , float):
            assert isinstance(metric1 , float) , f'metric1 should be a float, but got {type(metric1)}'
            return metric0 > metric1 if metric_type == 'accuracy' else metric0 < metric1
        elif isinstance(metric0 , (dict , EpochMetricResult)):
            if isinstance(metric0 , EpochMetricResult):
                metric0 = metric0.metrics('valid' , metric_type)
            if isinstance(metric1 , EpochMetricResult):
                metric1 = metric1.metrics('valid' , metric_type)
            assert isinstance(metric0 , dict) and isinstance(metric1 , dict) , f'metric0 and metric1 should be a dict, but got {type(metric0)} and {type(metric1)}'
            if metric_type == 'accuracy':
                agg = self.accuracy_aggregator(aggregator)
                return agg.accuracy(metric0) > agg.accuracy(metric1)
            else:
                agg = self.loss_aggregator(aggregator)
                return agg.loss_item(metric0) < agg.loss_item(metric1)
        else:
            raise ValueError(f'Invalid metric: {metric_type}')

    def compile_results(self , metrics : Iterable[EpochMetricResult] , metric_type : Literal['accuracy','loss'] = 'accuracy' , aggregator : AggregatorType | None = None) -> np.ndarray:
        return np.array([self.total_accuracy(metric.metrics('valid' , metric_type) , aggregator) for metric in metrics])

