seqlens:        [{day: 1}] # although not a param for model, but can be different values(dict of SEQLEN) #
linear_tree:    [False]    # constant leaves; linear_tree extrapolates in sparse / extreme-feature regions
learning_rate:  [0.05]
num_boost_round: [2000]
early_stopping: [100]
reg_lambda:     [1.0]
reg_alpha:      [0.1]
num_leaves:     [31]
max_depth:      [6]
min_data_in_leaf:         [200]
min_sum_hessian_in_leaf:  [10]
path_smooth:              [1.0]
max_bin:                  [127]
feature_fraction:         [0.6]
feature_fraction_bynode:  [0.8]
bagging_fraction:         [0.8]
bagging_freq:             [1]  # bagging_fraction is ignored unless this is > 0
force_col_wise:           [True]
monotone_constraints:     [0]
