hidden_dim:              [64]
num_experts:             [3]
num_market_aware_experts: [1]
dropout:                 [0.1]
enc_in:                  [true]
enc_att:                 [false]
rnn_type:                ['gru']
rnn_layers:              [2]
gate_rnn_layers:         [1]
dec_mlp_layers:          [2]
num_output:              [1]
which_output:            [null]
hidden_as_factor:        [true]
load_balance_weight:     [0.01]
diversity_weight:        [0.001]
