# basic verbosity settings
basic:
  vb: 3
  vb_max: 10
  vb_min: 0
  vb_never: 99
  vb_always: -99
  
# special verbosity settings for special purposes , use Proj.vb.get('key') to get the verbosity
special:
  callback: 
    default: never
    debug: always
  proxy:
    default: max
    debug: always
  crawler:
    default: max
    debug: always