name: null # gru_2head # null
module: lgbm # hidden_aggregator # 'LSTM' # 'TRA_LSTM' # 'GeneralRNN' # patch_tst # lgbm , gru_dsize
submodels: [best , swalast , swabest]

booster_head: null # lgbm , ada , xgboost , catboost
booster_type: lgbm # ada , xgboost , catboost

labels: 
  - std_lag1_10 # rtn_lag1_10 # std_lag1_10
  - rtn_lag1_10 # rtn_lag1_20 # std_lag1_20

input_type: hidden # data or hidden

data.types: day # 'day+30m' , 30m , day
data.prenorm:
  day: {'divlast' : True  , 'histnorm' : True}

hidden.types:
  - gru_day.0.best

beg_date:   20170103 # 20220613 # 20170103
end_date:   99991231
interval:   20 # 120
train_window:    2400

