max_epoch:  200
batch_size: 10000
skip_horizon:  20 # must be larger than span of labels 
data_step:  5

dataloader.sample_method:   sequential # total_shuffle , sequential , both_shuffle , train_shuffle
dataloader.shuffle_option:  epoch # static , init , epoch
dataloader.train_ratio:     0.8

trainer.transfer:  false
trainer.optimizer: {'name' : 'Adam' , 'param' : {} ,}  #{'name' : 'SGD' , 'param' : {} ,}
trainer.scheduler: {'name' : 'cycle' , 'param' : {'base_lr': 1.0e-7 , 'step_size_up': 4} ,}  #{'name' : 'SGD' , 'param' : {} ,}
trainer.learn_rate: {'base' : 0.005 , 'transfer_multiplier' : {'encoder' : 0.1 , 'decoder' : 1.0, }}
trainer.gradient.clip_value: 10.0

criterion.loss:      ccc  # mse, pearson, ccc
criterion.score:     spearman # mse, pearson, ccc, spearman
criterion.penalty:   
  hidden_corr:  {'lamb' :  0.001 ,}
criterion.weight.fit:    'equal' # 'top'
criterion.weight.test:   'equal' # 'top'

multilosses.type: hybrid
multilosses.param.dwa: {'tau' : 2}
multilosses.param.ruw: {'phi' : null}
multilosses.param.ewa: {}
multilosses.param.gls: {}
multilosses.param.rws: {}
multilosses.param.hybrid: {'phi' : null , 'tau' : 2}